id: simpledrawer
name: SimpleDrawer
version: "1.8.2"
description: A datapack that add drawers in to minecraft
author: AirDox_



data_pack:
  load: [.]
resource_pack:
  load: [.]

pipeline:
  - simpledrawer.add_mc_version_support

extend: [common.yaml]

meta:
  mc_supports: ["1.20","1.20.1"]
  mc_supports_dataversion: [3463,3465]
  smithed_dependencies:
    - id: "smithed:crafter"
      version: "0.2.0"
    - id: "smithed:actionbar"
      version: "0.4.1"
    - id: "airdox_:itemio"
      version: "0.5.3"