id: simpledrawer
name: SimpleDrawer
version: "1.11.2"
description: A datapack that add drawers in to minecraft
author: AirDox_

output: "build"

overrides:
  - meta.smithed.versioning.scheduled_paths: [impl/tick,impl/5tick,impl/20tick,impl/mc_version_check,impl/timestamp]

data_pack:
  load: [.]
resource_pack:
  load: [.]

pipeline:
  - simpledrawer.add_mc_version_support
  - simpledrawer.add_versioning_to_items
  - airdox_.test_load_generator
  - airdox_.cache_dependencies
  - airdox_.load_included

extend: "common.yaml"

meta:
  modrinth_id: "JmCxCKiW"
  mc_supports: ["1.20.2"]
  mc_supports_dataversion: [3578]
  weld_deps:
    enable_weld_merging: True
    clean_load_tag: False
    include_prerelease: False
    deps:
      - id: "custom-block"
        match: ">0.0.0"
        source: "smithed"
      - id: "itemio"
        match: ">0.9.0"
        source: "smithed"
      - id: "code-of-copper"
        match: ">0.1.0"
        source: "modrinth"