id: simpledrawer
name: SimpleDrawer
description: A datapack that add drawers in to minecraft
author: AirDox_

output: "build"

overrides:
  - meta.smithed.versioning.scheduled_paths: [impl/tick,impl/5tick,impl/20tick,impl/mc_version_check,impl/timestamp]

data_pack:
  load: [.]
resource_pack:
  load: [.]

require:
  - weld_deps
  
pipeline:
  - guide
  - pack
  - simpledrawer.add_mc_version_support
  - simpledrawer.add_versioning_to_items
  - simpledrawer.generate_translation
  - airdox_.test_load_generator
  - airdox_.monkey_patch_1_21

extend: "common.yaml"

meta:
  model_resolver:
    render_size: 256
    load_vanilla: true
    save_namespace: "simpledrawer"
  modrinth_id: "JmCxCKiW"
  mc_supports: ["1.21"]
  mc_supports_dataversion: [3953]
  weld_deps:
    enable_weld_merging: True
    clean_load_tag: True
    include_prerelease: False
    deps:
      - id: "itemio"
        match: ">=1.0.0"
        source: "smithed"
        versioning: 
          type: "normal"
          prefix: "#itemio"
      - id: "smithed.crafter.dev"
        match: ">=0.4.0"
        source: "smithed"
        versioning: 
          type: "normal"
          prefix: "#smithed.crafter"
      - id: "smithed.custom_block.dev"
        match: ">=0.4.0"
        source: "smithed"
        versioning: 
          type: "normal"
          prefix: "#smithed.custom_block"