id: simpledrawer
name: SimpleDrawer
version: "1.8.2"
description: A datapack that add drawers in to minecraft
author: AirDox_



data_pack:
  load: [.]
resource_pack:
  load: [.]

pipeline:
  - simpledrawer.add_mc_version_support
  - simpledrawer.add_versioning_to_items
  - airdox_.test_load_generator

extend: [common.yaml]

meta:
  mc_supports: ["1.20","1.20.1"]
  mc_supports_dataversion: [3463,3465]
  smithed_dependencies:
    - id: "smithed:crafter"
      version_: "0.2.0"
      versioning:
        type: "normal"
        prefix: "#smithed.crafter."

    - id: "smithed:custom_block"
      version_: "0.2.0"
      versioning:
        type: "normal"
        prefix: "#smithed.custom_block."

    - id: "smithed:actionbar"
      version_: "0.4.1"
      versioning:
        type: "normal"
        prefix: "#smithed.actionbar."

    - id: "airdox_:itemio"
      version_: "0.5.3"
      versioning:
        type: "normal"
        prefix: "#itemio."
        