id: simpledrawer
name: SimpleDrawer
version: "1.9.0"
description: A datapack that add drawers in to minecraft
author: AirDox_

overrides:
  - meta.smithed.versioning.scheduled_paths: [impl/tick,impl/5tick,impl/20tick,impl/mc_version_check]

data_pack:
  load: [.]
resource_pack:
  load: [.]

pipeline:
  - simpledrawer.add_mc_version_support
  - simpledrawer.add_versioning_to_items
  - airdox_.test_load_generator

extend: "@airdox_/common.yaml"

meta:
  mc_supports: ["1.20","1.20.1"]
  mc_supports_dataversion: [3463,3465]
  smithed_dependencies:
    - id: "smithed:crafter"
      version_: "0.2.0"
      versioning:
        type: "normal"
        prefix: "#smithed.crafter."

    - id: "smithed:custom-block"
      version_: "0.2.0"
      versioning:
        type: "normal"
        prefix: "#smithed.custom_block."

    - id: "smithed:actionbar"
      version_: "0.4.1"
      versioning:
        type: "normal"
        prefix: "#smithed.actionbar."

    - id: "airdox_:itemio"
      version_: "0.5.3"
      versioning:
        type: "normal"
        prefix: "#itemio."
        