id: simpledrawer
name: SimpleDrawer
description: A datapack that add drawers in to minecraft
author: AirDox_

output: "build"

overrides:
  - meta.smithed.versioning.scheduled_paths: [impl/tick,impl/5tick,impl/20tick,impl/mc_version_check,impl/timestamp]

data_pack:
  pack_format: 57
  supported_formats: [57, 61]
  load: [.]
resource_pack:
  pack_format: 42
  supported_formats: [42, 46]
  load: [.]

require:
  - weld_deps
  
pipeline:
  - guide
  - pack
  - simpledrawer.add_mc_version_support
  - simpledrawer.add_versioning_to_items
  - simpledrawer.generate_translation
  - airdox_.test_load_generator

extend: "common.yaml"

meta:
  model_resolver:
    render_size: 256
    load_vanilla: true
    save_namespace: "simpledrawer"
  modrinth_id: "JmCxCKiW"
  mc_supports: ["1.21.4"]
  mc_supports_dataversion: [4189]
  weld_deps:
    enable_weld_merging: True
    clean_load_tag: True
    include_prerelease: False
    deps:
      - id: "itemio"
        version: "1.3.3"
        source: "smithed"
        versioning: 
          type: "normal"
          prefix: "#itemio"
      - id: "crafter"
        version: "0.6.2"
        source: "smithed"
        versioning: 
          type: "normal"
          prefix: "#smithed.crafter"
      - id: "custom-block"
        version: "0.6.2"
        source: "smithed"
        versioning: 
          type: "normal"
          prefix: "#smithed.custom_block"