extend: ["../../beet.yaml"]

output: "../../build/"

data_pack:
  name: "datapack-bundled"
  zipped: false

resource_pack:
  name: "resourcepack-bundled"
  zipped: false


pipeline:
  -
    data_pack:
      load: ["../included/*"]
    pipeline: ["airdox_.delete_load_tag_and_packpng"]
  -
    resource_pack:
      load: ["../included/*"]
    pipeline: ["airdox_.delete_load_tag_and_packpng"]
