extend: ["../../beet.yaml"]

output: "../../build/"

data_pack:
  name: "{{ project_name }}-v{{ project_version }}-Datapack-Bundled"
  zipped: true

resource_pack:
  name: "{{ project_name }}-v{{ project_version }}-Resourcepack-Bundled"
  zipped: true


pipeline:
  - airdox_.load_included

